// src/app/layout.tsx
import "./globals.css";
import Dock from "@/components/Dock";
import CommandPalette from "@/components/CommandPalette";

export const metadata = { title: "Chris Meseha | Front-End Dev" };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-white text-gray-900 dark:bg-black dark:text-white">
        {/** global UI */}
        <Dock />
        <CommandPalette />

        {/* top & bottom shadow – pointer-events:none so it never steals scroll */}
        <div
          className="pointer-events-none fixed inset-x-0 top-0 h-40
                        bg-gradient-to-b from-black/60 to-transparent z-20"
        />
        <div
          className="pointer-events-none fixed inset-x-0 bottom-0 h-40
                        bg-gradient-to-t from-black/60 to-transparent z-20"
        />

        {/* page sections mount here */}
        {children}
      </body>
    </html>
  );
}

//import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
//
//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//});
//
//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});
//
//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};
//
//export default function RootLayout({
//  children,
//}: Readonly<{
//  children: React.ReactNode;
//}>) {
//  return (
//    <html lang="en">
//      <body
//        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//      >
//        {children}
//      </body>
//    </html>
//  );
//}
//
